### ISSUE TITLE
Fix for Symfony 3.1+ deprecation

### ISSUE THREAD

**Issue by ninsky** [wow-apps/symfony-slack-bot#1]
Hi

Symfony 3.1+ needs arguments starting with a % character to be quoted. I'm getting following deprecation message in my Symfony 3.3 project:

> Not quoting the scalar "%wowapps.slackbot.config%" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0

Would be nice if you could put following little change to the service.yml:

Old:
`arguments: [%wowapps.slackbot.config%]`

New:
`arguments: ["%wowapps.slackbot.config%"]`

That should fix it! 

Thanks in advance
Nino

**Comment by wow-apps** [comment]
Thank you @ninsky , in a week I plan to prepare compatibility to version 4 of Symfony.

**Comment by wow-apps** [comment]
Fixed in version 3.1.0
