### ISSUE TITLE
Slack responds with Code 400

### ISSUE THREAD

**Issue by upMKuhn** [wow-apps/symfony-slack-bot#10]
**Describe the bug**
Slack responds with Error code 400, because Slackbot is not setting the application\json header.

**To Reproduce**
Try to send a test message ;) 
Client error: `POST hooks.slack.com/services/myHook` resulted in a `400 Bad Request` response  
  :                                                                                                                                    
  invalid_payload               

**Versions (please complete the following information):**
 - OS: Linux
 - Symfony 3.4
 - wow-apps/symfony-slack-bot ^3.2
 - Guzzle: 6.3

**Comment by upMKuhn** [comment]
The problem was the protocol was missing and the curl I copied to experiment with the request contained it :D

**Comment by wow-apps** [comment]
@upMKukn - I've test, everything work for me.
I see, that you close an issue, hope you found a problem
