### ISSUE TITLE
Can't add text with links

### ISSUE THREAD

**Issue by lightglitch** [wow-apps/symfony-slack-bot#11]
**Describe the bug**

By escaping all the text in the setter we can't add links to the message because the link syntax is escaped.

**To Reproduce**
```
$slackMessage->setText("Test link: ".$this->formatLink('Google', 'http://www.google.com'));
```

**Comment by wow-apps** [comment]
@lightglitch thanks, I'll check it

**Comment by wow-apps** [comment]
**Fixed**
