### ISSUE TITLE
Flex recipe in Symfony 3.4 throws an error, breaks application

### ISSUE THREAD

**Issue by YetiCGN** [wow-apps/symfony-slack-bot#3]
Installing symfony-slack-bot via Composer in a Symfony 3.4 project throws the following error:

`The file "services.yaml" does not exist (in: \github\churchtools-slack-bot\vendor\wow-apps\symfony-slack-bot\DependencyInjection/../Resources/config).`

Quick fix: Creating an empty file in the vendor directory under "Resources/config/services.yaml". The recipe did not complete, however as the services are not registered. In addition, required parameters under `wow_apps_slack` in `wow_apps_slack.yaml` are missing, such as `quote_color`.

Platform: Windows 10

**Comment by NeoBlack** [comment]
same problem with OSX

**Comment by TomasHermanek** [comment]
same problem with Ubuntu 18.04, using Symfony 3.4

**Comment by wow-apps** [comment]
hm ... I'll check it on this weekend. Thanks for alerting

**Comment by jvc9109** [comment]
@YetiCGN Apparently the composer installation is not importing the repo file config/services.yaml. Instead of creating an empty service.yaml, copypaste the one from this repo.

**Comment by wow-apps** [comment]
Sorry guys, just found a free time to fix that and test on different versions. Update is coming...

**Comment by wow-apps** [comment]
@YetiCGN or @NeoBlack or @TomasHermanek 
could you tell me your Composer version?

**Comment by NeoBlack** [comment]
Composer version 1.6.5 2018-05-04 11:44:59

**Comment by wow-apps** [comment]
- Symfony 3.4.14
- PHP 7.1.16 (cli)
- Composer version 1.6.5 2018-05-04 11:44:59
- MacOS 10.13.6 (17G65)

![image](https://user-images.githubusercontent.com/2779949/44474677-ea5c5100-a63b-11e8-9d04-268ce372b37a.png)
![image](https://user-images.githubusercontent.com/2779949/44475001-9f8f0900-a63c-11e8-9da7-35548b3ded7c.png)


Problem exists. Probably it comes with receipt ... but I need to check...

**Comment by wow-apps** [comment]
Created an issue in symfony/recipes

https://github.com/symfony/recipes-contrib/issues/459

**Comment by xabbuh** [comment]
The config file was committed in 2524102f5926fbb20944a6d784d6505daa05ba8f, but the latest release 3.2.3 does not contain this commit.

**Comment by wow-apps** [comment]
@xabbuh thank you, I've missed it somehow
There was commit, but tag 3.2.4 not added
Fix will arrive in 3.2.5
