### ISSUE TITLE
You have requested a non-existent service "wowapps.slackbot".

### ISSUE THREAD

**Issue by maykino** [wow-apps/symfony-slack-bot#5]
I get this when I run "php bin/console wowapps:slackbot:test"

What could be wrong?

**Comment by wow-apps** [comment]
@maykino please tell me next information:
- Composer version
- PHP version
- Symfony version

Or attach composer.json file

Thanks!

**Comment by wow-apps** [comment]
@maykino try to update the bundle... maybe you have problem from 3.2.3, that was fixed in 3.2.5 (https://github.com/wow-apps/symfony-slack-bot/issues/3)

If not, open new issue with more description
