### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by thickey256** [wow-apps/symfony-slack-bot#9]
**Describe the bug**
Using
```$slackMessage->setIcon(':poop:'); ```
or
```$slackMessage->setIcon('http://lorempixel.com/48/48	');```
doesn't end up making it to the final posted json.

**Verbose**
I added $return['icon_emoji'] = $slackMessage->getIcon(); into the buildPostBody function which worked for emoji, but didn't for a image url, the variable for that in a slack message seems to be $return['icon_url'] .  I *think* a better option would be to have a setEmojiIcon() and setImageIcon() functions would be a better way to do this otherwise you are having to detect slack emoji strings or urls which is a bit messy.

Also you need to add JSON_UNESCAPED_SLASHES to the json_encode or it adds extra slashes to an image URL

``` return json_encode($return, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);```
I would have created a pull request but I didn't want to make a major change to the icons.   Also I didn't have much luck with an image icon,  I think it has something to do with the ```as_user``` and ```icon_url``` variables mentioned [here](https://api.slack.com/methods/chat.postMessage).

**Comment by wow-apps** [comment]
@thickey256 thanks for report. I'll check it in a few days

**Comment by wow-apps** [comment]
@thickey256 thank you again for your attention.

**Problem was solved in version 3.2.12**

### Here's change log:
**Changed**
- Fixed setting of message icon ([Issue #9](https://github.com/wow-apps/symfony-slack-bot/issues/9))
- Functions `setIcon` and `getIcon` for SlackBot DTO set as deprecated and will be removed in version 3.3 ([Issue #9](https://github.com/wow-apps/symfony-slack-bot/issues/9))
- Test command now send message with random emoji as icon

**Added**
- Functions `getIconUrl`, `setIconUrl`, `getIconEmoji` and `setIconEmoji`
- Class `SlackEmoji` with many constants of Slack emojis
- Flag `JSON_UNESCAPED_SLASHES` for outgoing message body ([Issue #9](https://github.com/wow-apps/symfony-slack-bot/issues/9))
- Emoji format validator
- Some new tests
